language: ruby
cache: bundler
sudo: false
rvm:
- 2.4.0

script: bundle exec jekyll build

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_deploy:
  - echo -e "|1|2XhH6IiSRzcpXmmi1xd0MW0Stnw=|DKnzppUong6ZGaZJFO10Ov+LSfI= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvmSM9cFyLTwaAQjf0j0bHZgsm7pBK/MJyLaaw04+RhW3F8MhvrVK+Zwb1V3q8R2R9s7OM6fkftje+6NbuNbuWqiqeScRamA+vVR2aTrUE7KqIsX2UL0QvVTBJQLEvH/BfyWgDjLx+J2biKXHcYQcoVaRRPkHC8ugKg0bGUHWdp+Bx9Bl0N2crZSUvz7kGm7+PrrXHe41eX8ZyUaxWZssf8/ldid7v2LeVverZD5DZcPGUsizYkBoyd9tQz9HAVfrRIS8oLJmrmTclK7pMy3f1I80BKwGCY2YQzkxIhTDftm7S74jOGYLd0nhVxhteFBhE7fwkN+TTtnkxRo8/VLcTw==\n" >> ~/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_382ed86ab497_key -iv $encrypted_382ed86ab497_iv -in travis_public_rsa.enc -out travis_public_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 travis_public_rsa
  - ssh-add travis_public_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz _site/ ckanich@bert.cs.uic.edu:/
  on:
    branch: master
